networks:
  servers:

services:
  balancer:
    build: .
    command: ["lb"]
    networks:
      - servers
    ports:
      - "8090:8090"
  db:
    build: .
    command: ["db"]
    networks:
      - servers
    ports:
      - "8083:8083"
      
  server1:
    build: .
    command: ["server"]
    networks:
      - servers
    ports:
      - "8080:8080"
  
  server2:
    build: .
    command: ["server"]
    networks:
      - servers
    ports:
      - "8081:8080"
  
  server3:
    build: .
    command: ["server"]
    networks:
      - servers
    ports:
      - "8082:8080"
