name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and test with docker compose
      run: |
        docker compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
        
    - name: Clean up
      if: always()
      run: |
        docker compose -f docker-compose.yaml -f docker-compose.test.yaml down -v
        docker system prune -f
